server:
  port: 8081

spring:
  application:
    name: tcc-monolito

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tcc_monolito?createDatabaseIfNotExist=True&useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect