server:
  port: 8081

topic:
  name: test2

#Colocar o nome do pod do MS para usar no feing, nesse caso o nome deste mesmo pod
aws:
  nomePodBookService: ${ec2-54-196-166-104.compute-1.amazonaws.com:8081}
  nomePodCambioService: ${ec2-54-196-166-104.compute-1.amazonaws.com:8081}


#POST localhost:8081/actuator/shutdown vai finalizar a aplicação
#Enable shutdown endpoint
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  application:
    name: tcc-monolito

  kafka:
    consumer:
      group-id: worker2
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: fatec.br.tccmonolitico.dtos.MessageConsumerDTO
    bootstrap-servers: ec2-18-234-142-221.compute-1.amazonaws.com:9091

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-44-203-164-111.compute-1.amazonaws.com:3336/tcc_monolito?createDatabaseIfNotExist=True&useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://ec2-44-203-164-111.compute-1.amazonaws.com:3336/
    schemas: tcc_monolito
    user: root
    password:
    locations: classpath:db/migration
